USE C_DB10_2018;
/*DROP TABLE ERP.RawProduct
DROP TABLE ERP.Product
DROP TABLE ERP.Process
DROP TABLE ERP.Customer*/

CREATE TABLE ERP.RawProduct(
	ID INT IDENTITY(1,1), 
	[Name] NVARCHAR(50) NOT NULL, 
	[Weight] FLOAT NOT NULL, 
	[DateOfPurchase] DateTime2 NOT NULL,
	CONSTRAINT RawProduct_ID PRIMARY KEY (ID)
)

CREATE TABLE [ERP].Product(
	ID INT IDENTITY(1,1),
	[Name] NVARCHAR(50) NOT NULL,
	[Weight] FLOAT NOT NULL,
	[Price] FLOAT NOT NULL,
	[Amount] FLOAT NOT NULL,
	[DateOfPackaging] DateTime2 NOT NULL,
	[DateOfExpiration] DateTime2 NOT NULL,
	CONSTRAINT Product_ID PRIMARY KEY (ID)
)

CREATE TABLE ERP.Process(
	ID INT IDENTITY(1,1),
	[Name] NVARCHAR(50) NOT NULL,
	[Weight] FLOAT NOT NULL,
	[DateOfProcess] DateTime2 NOT NULL,
	[Loss] FLOAT NOT NULL,
	CONSTRAINT Process_ID PRIMARY KEY (ID)
)

CREATE TABLE ERP.Customer(
	ID INT IDENTITY(1,1),
	[CompanyName] NVARCHAR(50) NOT NULL,
	[ProductOwner] NVARCHAR(50) NOT NULL,
	[Address] NVARCHAR(50) NOT NULL,
	[Zip] NVARCHAR(10) NOT NULL,
	[Town] NVARCHAR(50) NOT NULL,
	[Telephone] NVARCHAR(20) NOT NULL,
	CONSTRAINT Customer_ID PRIMARY KEY (ID)
)