USE C_DB10_2018;

CREATE TABLE ERP.[Order](
	OrderID INT IDENTITY(1,1), 
	CustomerID INT NOT NULL,
	DateOfPurchase DateTime2 NOT NULL, 
	TotalPrice FLOAT NOT NULL, 
	CONSTRAINT OrderID_PK PRIMARY KEY (OrderID),
	CONSTRAINT OrderCustomerID_FK FOREIGN KEY (CustomerID) REFERENCES ERP.Customer(CustomerID)
)

CREATE TABLE ERP.Offer(
	OfferID INT IDENTITY(1,1),
	CustomerID INT NOT NULL,
	DateOfOffer DateTime2 NOT NULL, 
	DateOfOfferExpirationDate DateTime2 NOT NULL, 
	TotalPrice FLOAT NOT NULL, 
	CONSTRAINT OfferID_PK PRIMARY KEY (OfferID),
	CONSTRAINT OfferCustomerID_FK FOREIGN KEY (CustomerID) REFERENCES ERP.Customer(CustomerID)
)

CREATE TABLE ERP.Line(
	LineID INT IDENTITY(1,1), 
	OrderID INT NOT NULL,
	ProductID INT NOT NULL,
	Amount FLOAT NOT NULL, 
	CONSTRAINT LineID_PK PRIMARY KEY (LineID),
	CONSTRAINT OrderID_FK FOREIGN KEY (OrderID) REFERENCES ERP.[Order](OrderID),
	CONSTRAINT ProductID_FK FOREIGN KEY (ProductID) REFERENCES ERP.Product(ProductID)
)

